config/routes.rb
Rails.application.routes.draw do
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/students', to: 'students#index'
  # get '/students/new', to: 'students#new'
  # get '/students/:id', to: 'students#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :find_student, only: [:show, :edit, :update, :destroy]
    
    
    def index #NEEDS ALL STUDENTS
        @students = Student.all  
        
    end
    
    #SHOW needs INSTANCE of logged STUDENT to display
    def show 
        # @student = Student.find(params[:id])
    end
    
    #NEW - FORM needs INSTANCE of Student.NEW , for UPDATE ACTION to instanciate a new student
    def new 
        @student = Student.new
    end
    
    #create
    def create
         @student = Student.create(student_params)
        redirect_to @student
    end



    #EDIT - FORM to take updated information for STUDENT:id pass it into UPDATE
    def edit 
        # @student  = Student.new
    end
    
    #UPDATE takes PARMAMS from EDIT FORM and updates Student:id info
    def update 
        # @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to @student
        
    end

    def destroy
        @student.destroy
        redirect_to students_path
    end
    
    
    
    #find student
    def find_student
        @student = Student.find(params[:id])
    end




    private
    def student_params
        params.require(:student).permit(:name, :age, :grade, :location)
      end
        
        
        
        
        
        



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Your information Here</h1>

<%= form_for @student do |form| %>

<p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </p>


  <p>
    <%= form.label :grade %><br>
    <%= form.text_field :grade %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%  %>
<%= button_to "Students Page", students_path,method: :get %>

app/views/students/index.html.erb
<h1>Welcome Students and Parents!</h1>

<h4>Check out our current student roster!</h4>

    <ul>
        <% @students.each do |student|%>
        <li>
        <a href="/students/<%= student.id %>">
            <%= student.name%>
        </a>
        </li>
        <% end %>

    </ul>

    <h2>Looking for a tutor?</h2>
    <%= button_to "Sign Up Here", new_student_path, method: :get %>

app/views/students/new.html.erb
<h1>This is the New Student Form</h1>
<div>
</div>
<p>
    <h5>Please Sign Up Here!</h5>
    
    <form action="/students" method="POST">
    
      <label for="student_name">Name:</label>
      <input type="text" name="student[name]" placeholder="name" id= "student_name">
    
      <label for="student_age">Age:</label>
      <input type="text" name="student[age]" placeholder="age" id= "student_age">
    


      <label for="student_grade">Grade</label>
      <input type="text" name="student[grade]" placeholder="grade" id= "student_grade">


    
      <label for="student_location">Location</label>
      <input type="text" name="student[location]" placeholder="location" id= "student_name">
    

    
      <input type="submit" name="submit"  value="submit">
  
    </form>

   


<div>
<p>
<%= button_to "Students Roster", students_path, method: :get %>
</p>
</div>

app/views/students/show.html.erb
<h1>This is the Show page</h1>
<div>

<p>
   Name: <%= @student.name %>
</p>

<p>
   Age: <%= @student.age %>

</p>

<p>
  Grade: <%= @student.grade %>
</p>

<p>
  City: <%= @student.location %>
</p>
</div>

<%= button_to "Edit Student", edit_student_path(@student), method: :get%>
<%= button_to "Bye Bye Scholar", @student, method: :delete %>
<%= button_to "Students Page", students_path ,method: :get %>